language: cpp

os:
  - linux
  - osx

ompiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build

script: bash travis/build.sh

jobs:
  include:
    - stage: test
      script: bash travis/test.sh
