language: cpp

os:
  - linux
  - osx

ompiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build

jobs:
  include:
    - stage: Build
      script: bash ../travis/build.sh
    - stage: Test
      script: bash ../travis/test.sh
