language: cpp

os:
  - linux
  - osx

env:
  global:
    - CODECOV_TOKEN="a304e6b7-f321-4bfc-b622-27bf15ed93b4"

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build

script:
  - bash ../travis/build.sh
  - bash ../travis/test.sh

after_success:
  - bash ../travis/codcov.sh
