language: cpp

os:
  - linux
  - osx

ompiler:
  - gcc
  - clang

addons:
  apt:
    packages: lcov

before_script:
  - mkdir build
  - cd build

script: bash ../travis.sh

after_success:
  # https://github.com/codecov/example-cpp11-cmake
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
