name: macOS

on:
  pull_request:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "doc/*"

jobs:
  build:
    name: Build & Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: 1) Pull submodules
        run: git submodule init && git submodule update

      - name: 2) Install MKL
        # run: bash ci/mkl_install_linux.sh
        run: echo "Temp disabled"

      - name: 3) Build & Test on Mac
        run: bash ci/build_test_mac.sh
