name: build

on:
  pull_request:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "doc/*"

jobs:
  build:
    name: CI Build & Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: 1) Pull submodules
        run: git submodule init && git submodule update

      # - name: 2) Configure aws
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: AKIATGUE5JHV5TX52MJP
      #     aws-secret-access-key: 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
      #     aws-region: us-east-2

      - name: 2) Install MKL
        run: bash ci/mkl_install_linux.sh

      - name: 4-A) Build & Test on Linux
        if: matrix.os == 'ubuntu-latest'
        run: bash ci/build_test_linux.sh

      - name: 4-B) Build & Test on Mac
        if: matrix.os == 'macos-latest'
        run: bash ci/build_test_mac.sh

      - name: 5) Upload coverage to Codecov (only on Linux)
        if: matrix.os == 'ubuntu-latest'
        run: bash ci/codecov.sh
