name: C/C++ CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake init
      run: cmake .
    - name: make
      run: make
  build-mac:
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v2
    - name: cmake init
      run: cmake .
    - name: make
      run: make
