name: tests

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "doc/*"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "doc/*"

jobs:
  build:
    name: Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: 1) Pull submodules
        run: git submodule init && git submodule update

      - name: 2) CMake configure
        run: bash ci/test.sh ${{matrix.os}}

      - name: 5) Upload coverage to Codecov (only on Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: bash ci/codecov.sh
