name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, l, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: 1) Pull submodules
        run: git submodule init && git submodule update

      - name: 2) CMake configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug  -DDEBUG_TEST=ON ..

      - name: 3) Build all targets
        run: cd build && make

      - name: 4) Run test scripts
        run: bash ci/test.sh

      - name: 5) Upload coverage to Codecov (only on Ubuntu)
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            bash ci/codecov.sh
          fi
        shell: bash
